---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---


## Setting options
```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```

## Load library
```{r}
library(codebook)
library(future)
library(dplyr)
```

## Prepare data for codebook
```{r prepare_codebook}
codebook_data_robustness = read.csv(file = "data/data_robustness.csv")[,-1]

codebook_data_robustness <- detect_missing(codebook_data,
    only_labelled = TRUE, # only labelled values are autodetected as
                                   # missing
    negative_values_are_missing = FALSE, # negative values are missing values
    ninety_nine_problems = TRUE,   # 99/999 are missing values, if they
                                   # are more than 5 MAD from the median
    )
```


## Create codebook for robustness data set
### Codebook for demographics
```{r}
codebook_demographics_robustness = codebook_data_robustness %>% select(sexual_orientation, country, language, age, sex, 
                                                 transgender, relationship_length, relationship_status)
                                        

codebook(codebook_demographics_robustness)
```


### Codebook for outcomes
```{r}
codebook_outcomes_robustness = codebook_data_robustness %>% select(interest_hookups,
                                                                   interest_nonsexrel,
                                                                   interest_monrel,
                                                                   interest_monrel,
                                                                   interest_altrel,
                                                                   interest_single,
                                                                   interest_parent,
                                                                   pref_imp_ks,
                                                                   pref_imp_att,
                                                                   pref_imp_fs,
                                                                   pref_imp_ca,
                                                                   pref_imp_ei,
                                                                   self_ks,
                                                                   self_att,
                                                                   self_fs,
                                                                   self_ca,
                                                                   self_ei)
                                        

codebook(codebook_outcomes_robustness)
```


### Codebook by sexual orientation for robustness data set
#### Asexuals
```{r}
# codebook_asexuals_robustness = codebook_data_robustness %>% filter(sexual_orientation == "Asexual") %>%
#                                                             select(sexual_orientation, country, language, age, sex,
#                                                             transgender, relationship_length, relationship_status, interest_hookups,
#                                                             interest_nonsexrel, interest_monrel, interest_monrel, interest_altrel,
#                                                             interest_single, interest_parent,
#                                                             pref_imp_ks, pref_imp_att,pref_imp_fs,
#                                                             pref_imp_ca, pref_imp_ei,
#                                                             self_ks, self_att, self_fs, self_ca, self_ei)
# 
# codebook(codebook_asexuals_robustness)
```

#### Heterosexuals
```{r}
# codebook_heterosexuals_robustness = codebook_data_robustness %>% filter(sexual_orientation == "Straight/Heterosexual") %>%
#                                                                  select(sexual_orientation, country, language, age, sex,
#                                                                  transgender, relationship_length, relationship_status, interest_hookups,
#                                                                  interest_nonsexrel, interest_monrel, interest_monrel, interest_altrel,
#                                                                  interest_single, interest_parent,
#                                                                  pref_imp_ks, pref_imp_att,pref_imp_fs,
#                                                                  pref_imp_ca, pref_imp_ei,
#                                                                  self_ks, self_att, self_fs, self_ca, self_ei)
# 
# codebook(codebook_heterosexuals_robustness)
```


### Codebook by gender
#### Women
```{r}
# codebook_women = codebook_data_robustness %>% filter(sex == "Women") %>% 
#                                            select(sexual_orientation, country, language, age, sex, 
#                                                   transgender, relationship_length, relationship_status, interest_hookups,
#                                                  interest_nonsexrel, interest_monrel, interest_monrel, interest_altrel,
#                                                  interest_single, interest_parent, 
#                                                  pref_imp_ks, pref_imp_att,pref_imp_fs,
#                                                  pref_imp_ca, pref_imp_ei,
#                                                  self_ks, self_att, self_fs, self_ca, self_ei)
# 
# codebook(codebook_men)  
```

#### Men 
```{r}
# codebook_men = codebook_data_robustness %>% filter(sex == "Men") %>% 
#                                            select(sexual_orientation, country, language, age, sex, 
#                                                   transgender, relationship_length, relationship_status, interest_hookups,
#                                                  interest_nonsexrel, interest_monrel, interest_monrel, interest_altrel,
#                                                  interest_single, interest_parent, 
#                                                  pref_imp_ks, pref_imp_att,pref_imp_fs,
#                                                  pref_imp_ca, pref_imp_ei,
#                                                  self_ks, self_att, self_fs, self_ca, self_ei)
# 
# codebook(codebook_men)  
```

#### Genderqueer/Nonbinary
```{r}
# codebook_genderqueer = codebook_data_robustness %>% filter(sex == "Men") %>% 
#                                            select(sexual_orientation, country, language, age, sex, 
#                                                   transgender, relationship_length, relationship_status, interest_hookups,
#                                                  interest_nonsexrel, interest_monrel, interest_monrel, interest_altrel,
#                                                  interest_single, interest_parent, 
#                                                  pref_imp_ks, pref_imp_att,pref_imp_fs,
#                                                  pref_imp_ca, pref_imp_ei,
#                                                  self_ks, self_att, self_fs, self_ca, self_ei)
# 
# codebook(codebook_genderqueer)  
```

