---
title: "Codebook"
output:
  html_document:
    toc: true
    toc_depth: 4
    toc_float: true
    code_folding: 'hide'
    self_contained: true
  pdf_document:
    toc: yes
    toc_depth: 4
    latex_engine: xelatex
editor_options: 
  chunk_output_type: console
---


## Setting options
```{r setup}
knitr::opts_chunk$set(
  warning = TRUE, # show warnings during codebook generation
  message = TRUE, # show messages during codebook generation
  error = TRUE, # do not interrupt codebook generation in case of errors,
                # usually better for debugging
  echo = TRUE  # show R code
)
ggplot2::theme_set(ggplot2::theme_bw())

```

## Load library
```{r}
library(codebook)
library(future)
library(dplyr)
```

## Prepare data for codebook
```{r prepare_codebook}
codebook_data = read.csv(file = "data/data_main.csv")[,-1]
codebook_data_robustness = read.csv(file = "data/data_robustness.csv")[,-1]

# omit the following lines, if your missing values are already properly labelled
# codebook_data <- detect_missing(codebook_data,
#     only_labelled = TRUE, # only labelled values are autodetected as
#                                    # missing
#     negative_values_are_missing = FALSE, # negative values are missing values
#     ninety_nine_problems = TRUE,   # 99/999 are missing values, if they
#                                    # are more than 5 MAD from the median
#     )
# 
# codebook_data_robustness <- detect_missing(codebook_data,
#     only_labelled = TRUE, # only labelled values are autodetected as
#                                    # missing
#     negative_values_are_missing = FALSE, # negative values are missing values
#     ninety_nine_problems = TRUE,   # 99/999 are missing values, if they
#                                    # are more than 5 MAD from the median
#     )
# If you are not using formr, the codebook package needs to guess which items
# form a scale. The following line finds item aggregates with names like this:
# scale = scale_1 + scale_2R + scale_3R
# identifying these aggregates allows the codebook function to
# automatically compute reliabilities.
# However, it will not reverse items automatically.
# codebook_data <- detect_scales(codebook_data)
# 
# 
# codebook_data$pref_imp_scale_kindsupp <- codebook_data %>% select(pref_imp_kind, pref_imp_supportive) %>% aggregate_and_document_scale()
# codebook_data$pref_imp_scale_attrac <- codebook_data %>% select(pref_imp_attractive_body, pref_imp_attractive_face) %>% aggregate_and_document_scale()
# codebook_data$pref_imp_scale_finansuccess <- codebook_data %>% select(pref_imp_financially_secure, pref_imp_successful_ambitous) %>% aggregate_and_document_scale()
# codebook_data$pref_imp_scale_confassert <- codebook_data %>% select(pref_imp_confident, pref_imp_assertive) %>% aggregate_and_document_scale()
# codebook_data$pref_imp_scale_eduintell <- codebook_data %>% select(pref_imp_educated, pref_imp_intelligence) %>% aggregate_and_document_scale()

```


## Create codebook for main data set
### Codebook for demographics
```{r codebook}
codebook_demographics = codebook_data %>% select(sexual_orientation, country, language, age, sex, 
                                                 transgender, relationship_length, relationship_status)
                                        

codebook(codebook_demographics)
```


### Codebook for outcomes
```{r}
codebook_outcomes = codebook_data %>% select(interest_hookups,
                                             interest_nonsexrel,
                                             interest_monrel,
                                             interest_monrel,
                                             interest_altrel,
                                             interest_single,
                                             interest_parent,
                                             pref_imp_ks,
                                             pref_imp_att,
                                             pref_imp_fs,
                                             pref_imp_ca,
                                             pref_imp_ei,
                                             pref_imp_sexually_experienced,
                                             self_ks,
                                             self_att,
                                             self_fs,
                                             self_ca,
                                             self_ei,
                                             self_sexually_experienced)
                                        

codebook(codebook_outcomes)
```


### Codebook by sexual orientation
#### Asexuals
```{r}
codebook_asexuals = codebook_data %>% filter(sexual_orientation == "Asexual") %>% 
                                      select(sexual_orientation,
                                             country, 
                                             language, 
                                             age, 
                                             sex, 
                                             transgender,
                                             relationship_length, 
                                             relationship_status,
                                             interest_hookups,
                                             interest_nonsexrel,
                                             interest_monrel,
                                             interest_monrel,
                                             interest_altrel,
                                             interest_single,
                                             interest_parent, 
                                             pref_imp_ks,
                                             pref_imp_att,
                                             pref_imp_fs,
                                             pref_imp_ca,
                                             pref_imp_ei,
                                             pref_imp_sexually_experienced,
                                             self_ks,
                                             self_att, 
                                             self_fs, 
                                             self_ca,
                                             self_ei,
                                             self_sexually_experienced)

codebook(codebook_asexuals)                               
```

#### Heterosexuals
```{r}
codebook_heterosexuals = codebook_data %>% filter(sexual_orientation == "Straight/Heterosexual") %>% 
                                           select(sexual_orientation, 
                                                  country, language, 
                                                  age, 
                                                  sex, 
                                                  transgender,
                                                  relationship_length,
                                                  relationship_status, 
                                                  interest_hookups,
                                                  interest_nonsexrel, 
                                                  interest_monrel,
                                                  interest_monrel,
                                                  interest_altrel,
                                                  interest_single, 
                                                  interest_parent, 
                                                  pref_imp_ks, 
                                                  pref_imp_att,
                                                  pref_imp_fs,
                                                  pref_imp_ca,
                                                  pref_imp_ei,
                                                  pref_imp_sexually_experienced,
                                                  self_ks,
                                                  self_att, 
                                                  self_fs, 
                                                  self_ca,
                                                  self_ei,
                                                  self_sexually_experienced)

codebook(codebook_heterosexuals)  
```

