---
title: "03_descriptives"
output: html_document
date: '2022-04-01'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library
```{r}
library(dplyr)
library(formr)
```

## Load data
```{r}
data_main = read.csv(file = "data/data_main.csv")[,-1]
```

## Descriptives
```{r}
# get means for variables in data frame 
# excluding missing values
sapply(data_main, mean, na.rm=TRUE)


library(psych)
describe(data_main) # über alle hinweg
describeBy(data_main, data_main$sexual_orientation) # für sexuelle Orientierung aufgeteilt


hist(data_main$interest_nonmonrel)
asexual = data_main %>% filter(sexual_orientation == "Asexual")
hetero =  data_main %>% filter(sexual_orientation == "Straight/Heterosexual")
hist(asexual$interest_nonmonrel)
hist(hetero$interest_nonmonrel)

hist(asexual$interest_single)
hist(hetero$interest_single)


hist(asexual$interest_altrel)
hist(hetero$interest_altrel)
```

### Demographic data
#### Sexual orientation
```{r}
table(data_main$sexual_orientation) # sexual orientation in absolute numbers
round(table(data_main$sexual_orientation)/sum(table(data_main$sexual_orientation)),2)*100 # sexual orientation in percent
```

#### Country
```{r}
table(data_main$country) # country in absolute numbers
round(table(data_main$country)/sum(table(data_main$country)),4)*100 # country in percent
table(is.na(data_main$country)) # no NAs 
```

#### Language
Chinese, Danish, English, French, German, Japanese, Portuguese, Russian, Spanish, Italian
```{r Language}
table(data_main$language) # language in absolute numbers
round(table(data_main$country)/sum(table(data_main$country)),4)*100 # country in percent
table(is.na(data_main$language)) #no NAs
```




### scale values, internal consistencies, and descriptives for scales
```{r}
#xxx
```

### zero-order correlations
```{r}
# # zero order correlations for offspring and parents based on averaged parent scores from per offspring data frame
# corr_prefs = rcorr(as.matrix(data_offspring %>% select(off_prefs_WT, off_prefs_VA, off_prefs_SR, off_prefs_CH,
#                                                    off_prefs_FO,parent_prefs_WT, parent_prefs_VA,
#                                                    parent_prefs_SR,parent_prefs_CH,  parent_prefs_FO)))
# 
# 
# # correlations rounded to 2 decimals
# round(corr_prefs[[1]],2)
# 
# # number of observations
# corr_prefs[[2]]
# 
# # p-values rounded to 4 decimals
# round(corr_prefs[[3]],4)


```

