---
title: "Notes"
output: html_document
date: '2022-05-20'
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Lifetime sexual partners
```{r}
# load data with lifetime sexual partners variable
fulldata_selected_plus_sexual_partner_variable = read.csv(file = "data/fulldata_selected_plus_sexual_partner_variable.csv")[,-1]
names(fulldata_selected_plus_sexual_partner_variable)
sexual_partner = fulldata_selected_plus_sexual_partner_variable %>% select("total_sex_partners", "total_sex_partners2")

# add id variable to sexual partner data set
sexual_partner$id = 1:94738

# add variables to data
data_prefs_plus_sexual_partner_variable = left_join(data_prefs, sexual_partner) # joined by id variable
```


# look at sexual partners variables
```{r}
# mean
data_prefs_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), mean, na.rm = T)

# sd
data_prefs_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), sd, na.rm = T)

# min
data_prefs_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), min, na.rm = T)

# max
data_prefs_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), max, na.rm = T)

# range
data_prefs_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), range, na.rm = T)

# median
data_prefs_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), median, na.rm = T)

# counts
table(data_prefs_plus_sexual_partner_variable$total_sex_partners)
table(data_prefs_plus_sexual_partner_variable$total_sex_partners2)

# correlation
cor(data_prefs_plus_sexual_partner_variable$total_sex_partners, data_prefs_plus_sexual_partner_variable$total_sex_partners2, method = "pearson", na.rm = TRUE) # funktioniert nicht --> warum?
cor.test(data_prefs_plus_sexual_partner_variable$total_sex_partners, data_prefs_plus_sexual_partner_variable$total_sex_partners2, method = "pearson", na.rm = T)
```


```{r}
cor.test(data_prefs_plus_sexual_partner_variable$total_sex_partners2, data_prefs_plus_sexual_partner_variable$pref_imp_sexually_experienced, method = "pearson", na.rm = T)
```


## for self-ratings

```{r}
# add variables to data
data_self_plus_sexual_partner_variable = left_join(data_self, sexual_partner) # joined by id variable
```

# look at sexual partners variables
```{r}
# mean
data_self_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), mean, na.rm = T)

# sd
data_self_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), sd, na.rm = T)

# min
data_self_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), min, na.rm = T)

# max
data_self_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), max, na.rm = T)

# range
data_self_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), range, na.rm = T)

# median
data_self_plus_sexual_partner_variable %>% group_by(sexual_orientation) %>%
  summarise_at(c("total_sex_partners", "total_sex_partners2"), median, na.rm = T)

# counts
table(data_self_plus_sexual_partner_variable$total_sex_partners)
table(data_self_plus_sexual_partner_variable$total_sex_partners2)

# correlation
cor(data_self_plus_sexual_partner_variable$total_sex_partners, data_self_plus_sexual_partner_variable$total_sex_partners2, method = "pearson", na.rm = TRUE) # funktioniert nicht --> warum?
cor.test(data_self_plus_sexual_partner_variable$total_sex_partners, data_self_plus_sexual_partner_variable$total_sex_partners2, method = "pearson", na.rm = T)
```


```{r}
cor.test(data_self_plus_sexual_partner_variable$total_sex_partners2, data_self_plus_sexual_partner_variable$self_sexually_experienced, method = "pearson", na.rm = T)
```

