---
title: "cramerV"
output: html_document
date: '2022-06-21'
editor_options: 
  chunk_output_type: console
---
## Library
```{r}
library(dplyr)
library(formr)
library(ggplot2)
library(psych)
library(rcompanion)
```

## Load data
```{r}
# matched samples
data_rel = read.csv(file = "data/data_rel.csv")[,-1]
data_prefs = read.csv(file = "data/data_prefs.csv")[,-1]
data_self = read.csv(file = "data/data_self.csv")[,-1]

# unmatched heterosexual sample (includes only heterosexuals because during psm no asexual was discarded)
data_rel_unmatched = read.csv(file = "data/data_rel_unmatched.csv")[,-1]
data_prefs_unmatched = read.csv(file = "data/data_prefs_unmatched.csv")[,-1]
data_self_unmatched = read.csv(file = "data/data_self_unmatched.csv")[,-1]

nrow(data_rel_unmatched)
describe.by(asex_v_umhetero_rel, asex_v_umhetero_rel$sexual_orientation)
nrow(data_prefs_unmatched)
describe.by(asex_v_umhetero_prefs, asex_v_umhetero_prefs$sexual_orientation)

# asexual sample 
asexuals_rel = data_rel %>% filter(sexual_orientation == "Asexual")
asexuals_prefs = data_prefs %>% filter(sexual_orientation == "Asexual")
asexuals_self = data_self %>% filter(sexual_orientation == "Asexual")

# matched heterosexual sample (also from partner preference psm sample)
heterosexuals_rel = data_rel %>%  filter(sexual_orientation == "Straight/Heterosexual")
heterosexuals_prefs = data_prefs %>%  filter(sexual_orientation == "Straight/Heterosexual")
heterosexuals_self = data_self %>%  filter(sexual_orientation == "Straight/Heterosexual")
```


## Create samples for each comparison:
```{r  }
# Asexuals v. matched heterosexuals: 
asex_v_hetero_rel = data_rel
asex_v_hetero_prefs = data_prefs
asex_v_hetero_self = data_self

# Asexuals v. unmatched heterosexuals:
asex_v_umhetero_rel = full_join(asexuals_rel, data_rel_unmatched)
asex_v_umhetero_prefs = full_join(asexuals_prefs, data_prefs_unmatched)
asex_v_umhetero_self = full_join(asexuals_self, data_self_unmatched)

# Matched heterosexuals v. unmatched heterosexuals:
# add variable matched (matched or unmatched) as grouping variable to data sets
data_rel_unmatched$matched = "unmatched"
heterosexuals_rel$matched = "matched"

data_prefs_unmatched$matched = "unmatched"
heterosexuals_prefs$matched = "matched"

data_self_unmatched$matched = "unmatched"
heterosexuals_self$matched = "matched"

# merge data sets
hetero_v_umhetero_rel = full_join(heterosexuals_rel, data_rel_unmatched)
hetero_v_umhetero_prefs = full_join(heterosexuals_prefs, data_prefs_unmatched)
hetero_v_umhetero_self = full_join(heterosexuals_self, data_self_unmatched)
```


## Asexuals v. unmatched heterosexuals
### Country
```{r}
# assumptions not met for chi square test: some cells contain less than 5 observations; therefore a Fisher's exact test ist calculated
matrix_asex_v_umhetero_country = as.matrix(table(asex_v_umhetero_prefs$country, asex_v_umhetero_prefs$sexual_orientation), header=TRUE, row.names=1)
table(matrix_asex_v_umhetero_country < 5) # absolute number of cells containing less than 5 counts
nrow(matrix_asex_v_umhetero_country) * 2 # number of cells

round(table(matrix_asex_v_umhetero_country<5)/(nrow(matrix_asex_v_umhetero_country)*2),2) # 64% of cells have counts less than 5 

# running Fisher's exact test
fisher_test_asex_v_umhetero_country = fisher.test(matrix_asex_v_umhetero_country)
fisher_test_country$p.value
```
@Problem Fehlermeldung bei Fisher exact test. N wahrscheinlich zu groß. 

```{r}
# chi square test
chisq_country = chisq.test(matrix_asex_v_umhetero_country) 
chisq_country 

# calculate Cramer V
cramerV(matrix_asex_v_umhetero_country) #without CI
cramerV(matrix_asex_v_umhetero_country, ci = T) # with CI
?cramerV
```
@Problem Fehlermeldung wenn Cramer V mit KI berechnet werden soll
