---
title: "Untitled"
output: html_document
date: '2022-09-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Ausprobieren
## Preferred relationship options
```{r, fig.width = 10, fig.height = 6}
base_data <- tibble(mean  = c(-0.67, 1.12, -0.46, 0.20, 0.57, 0.61, -0.77), 
                    lower = c(-0.83, 0.93, -0.61, 0.05, 0.41, 0.45, -0.94),
                    upper = c(-0.51, 1.32, -0.31, 0.35, 0.73, 0.76, -0.61),
                    Preferred_relationship_options = c("Sexual, non-romantic", "Non-sexual, romantic", "Monogamous", "Non-monogamous", "Alternative committed", "Being non-partnered", "Becoming a parent"),
                    d = c("-0.67", "1.12", "-0.46", "0.20", "0.57", "0.61", "-0.77"))

summary <- tibble(mean  = 0.09,
                  lower = 0,
                  upper = 0.5,
                  Preferred_relationship_options = "Summary",
                  d = "0.09",
                  summary = TRUE)

header <- tibble(Preferred_relationship_options = c("", "Preferred relationship options"),
                d = c("", "d"),
                 summary = TRUE)

empty_row <- tibble(mean = NA_real_)

preferred_relationship_options <- bind_rows(header,
                                base_data,
                                empty_row,
                                summary)



preferred_relationship_options  %>% 
  forestplot(labeltext = c(Preferred_relationship_options, d), 
             graph.pos = 3,
              clip = c(-1,2),
             lty.ci = 2,
             boxsize = .25,
              is.summary = summary,
              grid = structure(c(-.1, .1), 
                              gp = gpar(lty = 2, col = "#CCCCFF")), 
              xticks = c(-.1, -0.5, -0.1,0, .1, .5, 1),
             col = fpColors(box = "royalblue",
                            line = "black",
                            summary = "royalblue"),
             xlab = "Effect size (Cohen's d)")
```


## Partner preferences
```{r, fig.width = 10, fig.height = 6}
base_data_prefs <- tibble(mean  = c(-0.37, -0.52, -0.66, -0.16, -0.21, 0.01), 
                    lower = c(-0.51, -0.66, -0.81, -0.30, -0.35, -0.12),
                    upper = c(-0.24, -0.37, -0.51, -0.02, -0.08, 0.15),
                    Partner_preferences = c("Confident-assertive", "Attractive", "Sexually experienced", "Kind-supportive", "Financially secure-successful", "Educated-intelligent"),
                    d = c("-0.37", "-0.52", "-0.66", "0.16", "-0.21", "0.01"))

round(mean(base_data_prefs$mean),2) # mean of means

summary <- tibble(mean  = -0.32,
                  lower = -.5,
                  upper = 0.5,
                  Partner_preferences = "Summary",
                  d = "-0.32",
                  summary = TRUE)

header <- tibble(Partner_preferences = c("", "Partner preferences"),
                d = c("", "d"),
                 summary = TRUE)

empty_row <- tibble(mean = NA_real_)

partner_preferences <- bind_rows(header,
                                base_data_prefs,
                                empty_row,
                                summary)



partner_preferences %>% 
  forestplot(labeltext = c(Partner_preferences, d), 
             graph.pos = 3,
              clip = c(-1,2),
             lty.ci = 2,
             boxsize = .25,
              is.summary = summary,
              grid = structure(c(-.1, .1), 
                              gp = gpar(lty = 2, col = "#CCCCFF")), 
             xticks = c(-.1, -0.5, -0.1,0, .1, .5, 1),
             col = fpColors(box = "royalblue",
                            line = "black",
                            summary = "royalblue"))
```


## Self-ratings
```{r, fig.width = 10, fig.height = 6}
base_data_self <- tibble(mean  = c(-0.43, -0.49, -0.65, -0.40, -0.45, -0.17), 
                    lower = c(-0.57, -0.63, -0.79, -0.54, -0.60, -0.31),
                    upper = c(-0.29, -0.34, -0.52, -0.25, -0.31, -0.04),
                    self_ratings = c("Confident-assertive", "Attractive", "Sexually experienced", "Kind-supportive", "Financially secure-successful", "Educated-intelligent"),
                    d = c("-0.43", "-0.49", "-0.65", "-0.40", "-0.45", "-0.17"))

round(mean(base_data_self$mean),2) # mean of means


header <- tibble(self_ratings = c("", "Self-ratings"),
                d = c("", "d"),
                 summary = TRUE)


self_ratings <- bind_rows(header,
                                base_data_self)



self_ratings %>% 
  forestplot(labeltext = c(self_ratings, d), 
             graph.pos = 3,
              clip = c(-2,2),
             lty.ci = 2,
             boxsize = .25,
             
```
## Preferred relationship options
```{r, fig.width = 10, fig.height = 6}
base_data <- tibble(mean  = c(-0.67, 1.12, -0.46, 0.20, 0.57, 0.61, -0.77), 
                    lower = c(-0.83, 0.93, -0.61, 0.05, 0.41, 0.45, -0.94),
                    upper = c(-0.51, 1.32, -0.31, 0.35, 0.73, 0.76, -0.61),
                    Preferred_relationship_options = c("Sexual, non-romantic", "Non-sexual, romantic", "Monogamous", "Non-monogamous", "Alternative committed", "Being non-partnered", "Becoming a parent"),
                    d = c("-0.67", "1.12", "-0.46", "0.20", "0.57", "0.61", "-0.77"))

summary <- tibble(mean  = 0.09,
                  lower = 0,
                  upper = 0.5,
                  Preferred_relationship_options = "Summary",
                  d = "0.09",
                  summary = TRUE)

header <- tibble(Preferred_relationship_options = c("", "Preferred relationship options"),
                d = c("", "d"),
                 summary = TRUE)

empty_row <- tibble(mean = NA_real_)

preferred_relationship_options <- bind_rows(header,
                                base_data,
                                empty_row,
                                summary)



preferred_relationship_options  %>% 
  forestplot(labeltext = c(Preferred_relationship_options, d), 
             graph.pos = 3,
              clip = c(-1,2),
             lty.ci = 2,
             boxsize = .25,
              is.summary = summary,
              grid = structure(c(-.1, .1), 
                              gp = gpar(lty = 2, col = "#CCCCFF")), 
              xticks = c(-.1, -0.5, -0.1,0, .1, .5, 1),
             col = fpColors(box = "royalblue",
                            line = "black",
                            summary = "royalblue"))
```


## Partner preferences
```{r, fig.width = 10, fig.height = 6}
base_data_prefs <- tibble(mean  = c(-0.37, -0.52, -0.66, -0.16, -0.21, 0.01), 
                    lower = c(-0.51, -0.66, -0.81, -0.30, -0.35, -0.12),
                    upper = c(-0.24, -0.37, -0.51, -0.02, -0.08, 0.15),
                    Partner_preferences = c("Confident-assertive", "Attractive", "Sexually experienced", "Kind-supportive", "Financially secure-successful", "Educated-intelligent"),
                    d = c("-0.37", "-0.52", "-0.66", "0.16", "-0.21", "0.01"))

round(mean(base_data_prefs$mean),2) # mean of means

summary <- tibble(mean  = -0.32,
                  lower = -.5,
                  upper = 0.5,
                  Partner_preferences = "Summary",
                  d = "-0.32",
                  summary = TRUE)

header <- tibble(Partner_preferences = c("", "Partner preferences"),
                d = c("", "d"),
                 summary = TRUE)

empty_row <- tibble(mean = NA_real_)

partner_preferences <- bind_rows(header,
                                base_data_prefs,
                                empty_row,
                                summary)



partner_preferences %>% 
  forestplot(labeltext = c(Partner_preferences, d), 
             graph.pos = 3,
              clip = c(-1,2),
             lty.ci = 2,
             boxsize = .25,
              is.summary = summary,
              grid = structure(c(-.1, .1), 
                              gp = gpar(lty = 2, col = "#CCCCFF")), 
             xticks = c(-.1, -0.5, -0.1,0, .1, .5, 1),
             col = fpColors(box = "royalblue",
                            line = "black",
                            summary = "royalblue"))
```


## Self-ratings
```{r, fig.width = 10, fig.height = 6}
base_data_self <- tibble(mean  = c(-0.43, -0.49, -0.65, -0.40, -0.45, -0.17), 
                    lower = c(-0.57, -0.63, -0.79, -0.54, -0.60, -0.31),
                    upper = c(-0.29, -0.34, -0.52, -0.25, -0.31, -0.04),
                    self_ratings = c("Confident-assertive", "Attractive", "Sexually experienced", "Kind-supportive", "Financially secure-successful", "Educated-intelligent"),
                    d = c("-0.43", "-0.49", "-0.65", "-0.40", "-0.45", "-0.17"))

round(mean(base_data_self$mean),2) # mean of means

summary <- tibble(mean  = -0.43,
                  lower = -.5,
                  upper = 0.5,
                  self_ratings = "Summary",
                  d = "-0.43",
                  summary = TRUE)

header <- tibble(self_ratings = c("", "Self-ratings"),
                d = c("", "d"),
                 summary = TRUE)

empty_row <- tibble(mean = NA_real_)

self_ratings <- bind_rows(header,
                                base_data_self,
                                empty_row,
                                summary)



self_ratings %>% 
  forestplot(labeltext = c(self_ratings, d), 
             graph.pos = 3,
              clip = c(-2,2),
             lty.ci = 2,
             boxsize = .25,
              is.summary = summary,
              grid = structure(c(-.26, .26), 
                              gp = gpar(lty = 2, col = "#CCCCFF")), 
             xticks = c(-1, -0.5,-0.26, 0, 0.26, .5, 1),
             col = fpColors(box = "royalblue",
                            line = "black",
                            summary = "royalblue"))

```


# possibility to save plot with high resolution
```{r}
Cairo::Cairo(
  35, #length
  25, #width
  file = paste("prefscairo", ".png", sep = ""),
  type = "png", #tiff
  bg = "white", #white or transparent depending on your requirement 
  dpi = 300,
  units = "cm" #you can change to pixels etc 
)
plot(plot_partner_preferences) #p is your graph object 
dev.off()
```




## Create plots for methods section
### Love plot for nnm in the partner preference sample
```{r}
# Using alternate variable names
v <- data.frame(old = c("distance", "language_chinese", "language_japanese", "language_german","language_english",
                        "language_italian", "language_danish", "language_spanish", "language_russian", "language_portuguese",
                        "language_french", "age", 
                        "relationship_status_Long-term", "relationship_status_No relationship", "relationship_status_Short-term",
                        "relationship_length"),
                new = c("Propensity score", "Chinese", "Japanese", "German", "English", "Italian", "Danish", 
                        "Spanish", "Russian", "Portuguese", "French", 
                        "Long-term relationship", "No relationship", "Dating/Sexual Relationship","Age",  "Relationship length"))

love.plot(bal.tab(nnm_without_country, m.threshold = 0.1),
          stat = "mean.diffs",
          grid = T,
          stars = "raw",
          abs = F,
          sample.names = c("Before matching", "After matching"),
          var.names = v) 

```

### Love plot comparing all matching algorithms for smd and vr
```{r}
# smds
love.plot(sexual_orientation ~ language + age + 
            relationship_status + relationship_length,
          data = data_main_nomiss,
          stat = "mean.diffs",
          grid = T,
          stars = "raw",
          abs = F,
          weights = list(w1 = get.w(om),
                         w2 = get.w(nnm),
                         w3 = get.w(nnm_25),
                         w4 = get.w(nnm_10)),
          thresholds = c(m = .1),
          s.d.denom = "pooled",
          sample.names = c("Unmatched", "Optimal matching", "Nearest-neighbor-matching", "Nearest-neighbor-matching with caliper = 0.25", "Nearest-neighbor-matching with caliper = 0.10"),
          var.names = v) 


# variance ratios
love.plot(sexual_orientation ~ language + age + 
            relationship_status + relationship_length,
          data = data_main_nomiss,
          stat = "variance.ratios",
          grid = T,
          stars = "raw",
          abs = F,
          weights = list(w1 = get.w(om),
                         w2 = get.w(nnm)),
          sample.names = c("Unadjusted", "Optimal Matching", "Nearest-Neighbor-Matching")) 
```
